<?xml version="1.0" encoding="utf-8"?><Database Name="Othello" Class="EntidadesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5PI871H;Initial Catalog=Othello;User ID=sa" SettingsObjectName="Modelo.Properties.Settings" SettingsPropertyName="OthelloConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pais" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="correoElectronico" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>